# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'framePrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from form_cliente import Ui_Cliente
from tela_cliente import Ui_clientes

class Ui_SISERP(object):
    def setupUi(self, SISERP):
        SISERP.setObjectName("SISERP")
        SISERP.resize(1042, 564)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SISERP.sizePolicy().hasHeightForWidth())
        SISERP.setSizePolicy(sizePolicy)
        SISERP.setMinimumSize(QtCore.QSize(1000, 350))
        SISERP.setMaximumSize(QtCore.QSize(1042, 564))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/erp/erp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SISERP.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SISERP)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 210, 291, 171))
        self.label.setStyleSheet("image: url(:/empresa/v914-ning-36.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 320, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Neufreit")
        font.setPointSize(23)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.bt_clientes = QtWidgets.QPushButton(self.centralwidget)
        self.bt_clientes.setGeometry(QtCore.QRect(0, 0, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_clientes.setFont(font)
        self.bt_clientes.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cliente/pessoa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_clientes.setIcon(icon1)
        self.bt_clientes.setIconSize(QtCore.QSize(32, 32))
        self.bt_clientes.setObjectName("bt_clientes")
        self.bt_fornecedores = QtWidgets.QPushButton(self.centralwidget)
        self.bt_fornecedores.setGeometry(QtCore.QRect(130, 0, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_fornecedores.setFont(font)
        self.bt_fornecedores.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/fornecedor/caminhao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_fornecedores.setIcon(icon2)
        self.bt_fornecedores.setIconSize(QtCore.QSize(32, 32))
        self.bt_fornecedores.setObjectName("bt_fornecedores")
        self.bt_vendas = QtWidgets.QPushButton(self.centralwidget)
        self.bt_vendas.setGeometry(QtCore.QRect(260, 0, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_vendas.setFont(font)
        self.bt_vendas.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/carro/carrinho2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_vendas.setIcon(icon3)
        self.bt_vendas.setIconSize(QtCore.QSize(32, 32))
        self.bt_vendas.setObjectName("bt_vendas")
        self.bt_produtos = QtWidgets.QPushButton(self.centralwidget)
        self.bt_produtos.setGeometry(QtCore.QRect(390, 0, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_produtos.setFont(font)
        self.bt_produtos.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/prod/produto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_produtos.setIcon(icon4)
        self.bt_produtos.setIconSize(QtCore.QSize(32, 32))
        self.bt_produtos.setObjectName("bt_produtos")
        self.bt_pagar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_pagar.setGeometry(QtCore.QRect(520, 0, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_pagar.setFont(font)
        self.bt_pagar.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pagar/receber.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_pagar.setIcon(icon5)
        self.bt_pagar.setIconSize(QtCore.QSize(32, 32))
        self.bt_pagar.setObjectName("bt_pagar")
        self.bt_banco = QtWidgets.QPushButton(self.centralwidget)
        self.bt_banco.setGeometry(QtCore.QRect(650, 0, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_banco.setFont(font)
        self.bt_banco.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/empresa/banco2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_banco.setIcon(icon6)
        self.bt_banco.setIconSize(QtCore.QSize(32, 32))
        self.bt_banco.setObjectName("bt_banco")
        self.bt_caixa = QtWidgets.QPushButton(self.centralwidget)
        self.bt_caixa.setGeometry(QtCore.QRect(780, 0, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_caixa.setFont(font)
        self.bt_caixa.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/caixa/pagar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_caixa.setIcon(icon7)
        self.bt_caixa.setIconSize(QtCore.QSize(32, 32))
        self.bt_caixa.setObjectName("bt_caixa")
        self.bt_sair = QtWidgets.QPushButton(self.centralwidget)
        self.bt_sair.setGeometry(QtCore.QRect(910, 0, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bt_sair.setFont(font)
        self.bt_sair.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/sair/sair2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_sair.setIcon(icon8)
        self.bt_sair.setIconSize(QtCore.QSize(32, 32))
        self.bt_sair.setObjectName("bt_sair")
        SISERP.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SISERP)
        self.statusbar.setObjectName("statusbar")
        SISERP.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(SISERP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 21))
        self.menubar.setObjectName("menubar")
        self.menuCadasrtro = QtWidgets.QMenu(self.menubar)
        self.menuCadasrtro.setObjectName("menuCadasrtro")
        self.menuOpera_es = QtWidgets.QMenu(self.menubar)
        self.menuOpera_es.setObjectName("menuOpera_es")
        self.menuCompra = QtWidgets.QMenu(self.menuOpera_es)
        self.menuCompra.setObjectName("menuCompra")
        self.menuFinanceiro = QtWidgets.QMenu(self.menubar)
        self.menuFinanceiro.setObjectName("menuFinanceiro")
        self.menuNotas_Fiscais = QtWidgets.QMenu(self.menuFinanceiro)
        self.menuNotas_Fiscais.setObjectName("menuNotas_Fiscais")
        self.menuConsultas = QtWidgets.QMenu(self.menubar)
        self.menuConsultas.setObjectName("menuConsultas")
        SISERP.setMenuBar(self.menubar)
        self.actionCliente = QtWidgets.QAction(SISERP)
        self.actionCliente.setObjectName("actionCliente")
        self.actionFronecedor = QtWidgets.QAction(SISERP)
        self.actionFronecedor.setObjectName("actionFronecedor")
        self.actionUsu_rios = QtWidgets.QAction(SISERP)
        self.actionUsu_rios.setObjectName("actionUsu_rios")
        self.actionEstoque = QtWidgets.QAction(SISERP)
        self.actionEstoque.setObjectName("actionEstoque")
        self.actionConsumo = QtWidgets.QAction(SISERP)
        self.actionConsumo.setObjectName("actionConsumo")
        self.actionCriar_Pedido_de_Compra = QtWidgets.QAction(SISERP)
        self.actionCriar_Pedido_de_Compra.setObjectName("actionCriar_Pedido_de_Compra")
        self.actionRealizar_Compra = QtWidgets.QAction(SISERP)
        self.actionRealizar_Compra.setObjectName("actionRealizar_Compra")
        self.actionCancelar = QtWidgets.QAction(SISERP)
        self.actionCancelar.setObjectName("actionCancelar")
        self.actionContas_a_Pagar = QtWidgets.QAction(SISERP)
        self.actionContas_a_Pagar.setObjectName("actionContas_a_Pagar")
        self.actionA_Receber = QtWidgets.QAction(SISERP)
        self.actionA_Receber.setObjectName("actionA_Receber")
        self.actionEntrada = QtWidgets.QAction(SISERP)
        self.actionEntrada.setObjectName("actionEntrada")
        self.actionSa_da = QtWidgets.QAction(SISERP)
        self.actionSa_da.setObjectName("actionSa_da")
        self.actionConsumo_2 = QtWidgets.QAction(SISERP)
        self.actionConsumo_2.setObjectName("actionConsumo_2")
        self.actionD_bitos = QtWidgets.QAction(SISERP)
        self.actionD_bitos.setObjectName("actionD_bitos")
        self.menuCadasrtro.addSeparator()
        self.menuCadasrtro.addAction(self.actionCliente)
        self.menuCadasrtro.addSeparator()
        self.menuCadasrtro.addAction(self.actionFronecedor)
        self.menuCadasrtro.addSeparator()
        self.menuCadasrtro.addAction(self.actionUsu_rios)
        self.menuCadasrtro.addSeparator()
        self.menuCompra.addAction(self.actionCriar_Pedido_de_Compra)
        self.menuCompra.addSeparator()
        self.menuCompra.addAction(self.actionRealizar_Compra)
        self.menuCompra.addSeparator()
        self.menuCompra.addAction(self.actionCancelar)
        self.menuOpera_es.addSeparator()
        self.menuOpera_es.addAction(self.menuCompra.menuAction())
        self.menuOpera_es.addSeparator()
        self.menuOpera_es.addAction(self.actionEstoque)
        self.menuOpera_es.addSeparator()
        self.menuOpera_es.addAction(self.actionConsumo)
        self.menuOpera_es.addSeparator()
        self.menuNotas_Fiscais.addAction(self.actionEntrada)
        self.menuNotas_Fiscais.addSeparator()
        self.menuNotas_Fiscais.addAction(self.actionSa_da)
        self.menuFinanceiro.addSeparator()
        self.menuFinanceiro.addAction(self.actionContas_a_Pagar)
        self.menuFinanceiro.addSeparator()
        self.menuFinanceiro.addAction(self.actionA_Receber)
        self.menuFinanceiro.addSeparator()
        self.menuFinanceiro.addAction(self.menuNotas_Fiscais.menuAction())
        self.menuFinanceiro.addSeparator()
        self.menuConsultas.addAction(self.actionConsumo_2)
        self.menuConsultas.addSeparator()
        self.menuConsultas.addAction(self.actionD_bitos)
        self.menubar.addAction(self.menuCadasrtro.menuAction())
        self.menubar.addAction(self.menuOpera_es.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuConsultas.menuAction())
        self.bt_sair.setToolTip("Sair")
    
        self.retranslateUi(SISERP)
        QtCore.QMetaObject.connectSlotsByName(SISERP)

        ############ BOTÕES DO SISTEMA #######################
        self.bt_sair.clicked.connect(self.sairSistema) #fecha o sistema
        self.bt_clientes.clicked.connect(self.telaCliente) #abre o formulário cliente
        self.actionCliente.triggered.connect(self.abreFormCliente) #abre o formulário cliente
        



    ########### FUNÇÕES DO SISTEMA #################
    #funcção que fecha o sistema
    def sairSistema(self):
        sys.exit()

    #abre a oformulario de cliente
    def abreFormCliente(self):
        self.Cliente = QtWidgets.QWidget()
        self.ui = Ui_Cliente()
        self.ui.setupUi(self.Cliente)
        self.Cliente.show()

    #abre a tela de clientes
    def telaCliente(self):
        self.clientes = QtWidgets.QWidget()
        self.ui = Ui_clientes()
        self.ui.setupUi(self.clientes)
        self.clientes.show()




    def retranslateUi(self, SISERP):
        _translate = QtCore.QCoreApplication.translate
        SISERP.setWindowTitle(_translate("SISERP", "SysERP"))
        self.label_2.setText(_translate("SISERP", "SySERP"))
        self.bt_clientes.setToolTip(_translate("SISERP", "Clientes"))
        self.bt_clientes.setText(_translate("SISERP", "Clientes"))
        self.bt_fornecedores.setText(_translate("SISERP", "Fornecedores"))
        self.bt_vendas.setText(_translate("SISERP", "Vendas"))
        self.bt_produtos.setText(_translate("SISERP", "Produtos"))
        self.bt_pagar.setText(_translate("SISERP", "Pagar"))
        self.bt_banco.setText(_translate("SISERP", "Banco"))
        self.bt_caixa.setText(_translate("SISERP", "Caixa"))
        self.bt_sair.setText(_translate("SISERP", "Sair"))
        self.menuCadasrtro.setTitle(_translate("SISERP", "Cadastro"))
        self.menuOpera_es.setTitle(_translate("SISERP", "Operações"))
        self.menuCompra.setTitle(_translate("SISERP", "Compra"))
        self.menuFinanceiro.setTitle(_translate("SISERP", "Financeiro"))
        self.menuNotas_Fiscais.setTitle(_translate("SISERP", "Notas Fiscais"))
        self.menuConsultas.setTitle(_translate("SISERP", "Consultas"))
        self.actionCliente.setText(_translate("SISERP", "Cliente"))
        self.actionFronecedor.setText(_translate("SISERP", "Fronecedor"))
        self.actionUsu_rios.setText(_translate("SISERP", "Usuários"))
        self.actionEstoque.setText(_translate("SISERP", "Estoque"))
        self.actionConsumo.setText(_translate("SISERP", "Consumo"))
        self.actionCriar_Pedido_de_Compra.setText(_translate("SISERP", "Criar Pedido de Compra"))
        self.actionRealizar_Compra.setText(_translate("SISERP", "Realizar Compra"))
        self.actionCancelar.setText(_translate("SISERP", "Cancelar"))
        self.actionContas_a_Pagar.setText(_translate("SISERP", "Contas a Pagar"))
        self.actionA_Receber.setText(_translate("SISERP", "A Receber"))
        self.actionEntrada.setText(_translate("SISERP", "Entrada"))
        self.actionSa_da.setText(_translate("SISERP", "Saída"))
        self.actionConsumo_2.setText(_translate("SISERP", "Consumo"))
        self.actionD_bitos.setText(_translate("SISERP", "Débitos"))

    


################# Imagens do Sistema ###################
import caixa
import carrinho
import cliente
import erp
import fornecedor
import logo
import pagar
import produto
import sair

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SISERP = QtWidgets.QMainWindow()
    ui = Ui_SISERP()
    ui.setupUi(SISERP)
    SISERP.show()
    sys.exit(app.exec_())